import type { ItemType } from "@/db/enums"

export const itemLocations: {
  name: string
  coordinates: number[]
  amount: number
  location: string
  hidden: boolean
  type: ItemType
}[] = [
  {
    name: "potion",
    coordinates: [1416, 4202],
    amount: 1,
    location: "route-102",
    hidden: true,
    type: "item",
  },
  {
    name: "max-revive",
    coordinates: [1064, 3836],
    amount: 1,
    location: "petalburg-city",
    hidden: false,
    type: "item",
  },
  {
    name: "ether",
    coordinates: [808, 4250],
    amount: 1,
    location: "petalburg-city",
    hidden: false,
    type: "item",
  },
  {
    name: "oran-berry",
    coordinates: [1624, 3992],
    amount: 2,
    location: "route-102",
    hidden: false,
    type: "berry",
  },
  {
    name: "pecha-berry",
    coordinates: [1640, 3992],
    amount: 2,
    location: "route-102",
    hidden: false,
    type: "berry",
  },
  {
    name: "rare-candy",
    coordinates: [936, 4264],
    amount: 1,
    location: "petalburg-city",
    hidden: true,
    type: "item",
  },
  {
    name: "antidote",
    coordinates: [376, 4152],
    amount: 1,
    location: "route-104",
    hidden: true,
    type: "item",
  },
  {
    name: "heart-scale",
    coordinates: [376, 4024],
    amount: 1,
    location: "route-104",
    hidden: true,
    type: "item",
  },
  {
    name: "potion",
    coordinates: [344, 3880],
    amount: 1,
    location: "route-104",
    hidden: true,
    type: "item",
  },
  {
    name: "poke-ball",
    coordinates: [584, 3850],
    amount: 1,
    location: "route-104",
    hidden: false,
    type: "ball",
  },
  {
    name: "oran-berry",
    coordinates: [472, 3656],
    amount: 2,
    location: "route-104",
    hidden: false,
    type: "berry",
  },
  {
    name: "pecha-berry",
    coordinates: [504, 3656],
    amount: 2,
    location: "route-104",
    hidden: false,
    type: "berry",
  },
  {
    name: "cheri-berry",
    coordinates: [168, 3400],
    amount: 2,
    location: "route-104",
    hidden: false,
    type: "berry",
  },
  {
    name: "oran-berry",
    coordinates: [168, 3368],
    amount: 2,
    location: "route-104",
    hidden: false,
    type: "berry",
  },
  {
    name: "poke-ball",
    coordinates: [168, 3144],
    amount: 1,
    location: "route-104",
    hidden: true,
    type: "ball",
  },
  {
    name: "poke-ball",
    coordinates: [168, 3144],
    amount: 1,
    location: "route-104",
    hidden: true,
    type: "ball",
  },
  {
    name: "potion",
    coordinates: [200, 3130],
    amount: 1,
    location: "route-104",
    hidden: false,
    type: "item",
  },
  {
    name: "super-potion",
    coordinates: [232, 3096],
    amount: 1,
    location: "route-104",
    hidden: true,
    type: "item",
  },
  {
    name: "x-accuracy",
    coordinates: [712, 3354],
    amount: 1,
    location: "route-104",
    hidden: false,
    type: "item",
  },
  {
    name: "pp-up",
    coordinates: [744, 3242],
    amount: 1,
    location: "route-104",
    hidden: false,
    type: "item",
  },
  {
    name: "cheri-berry",
    coordinates: [664, 3096],
    amount: 2,
    location: "route-104",
    hidden: false,
    type: "berry",
  },
  {
    name: "leppa-berry",
    coordinates: [696, 3096],
    amount: 2,
    location: "route-104",
    hidden: false,
    type: "berry",
  },
  {
    name: "repel",
    coordinates: [920, 2314],
    amount: 1,
    location: "route-116",
    hidden: false,
    type: "item",
  },
  {
    name: "ether",
    coordinates: [1064, 2138],
    amount: 1,
    location: "route-116",
    hidden: false,
    type: "item",
  },
  {
    name: "potion",
    coordinates: [1304, 2154],
    amount: 1,
    location: "route-116",
    hidden: false,
    type: "item",
  },
  {
    name: "super-potion",
    coordinates: [1112, 2184],
    amount: 1,
    location: "route-116",
    hidden: true,
    type: "item",
  },
  {
    name: "pinap-berry",
    coordinates: [1048, 2072],
    amount: 3,
    location: "route-116",
    hidden: false,
    type: "berry",
  },
  {
    name: "chesto-berry",
    coordinates: [1064, 2072],
    amount: 2,
    location: "route-116",
    hidden: false,
    type: "berry",
  },
  {
    name: "chesto-berry",
    coordinates: [1080, 2072],
    amount: 2,
    location: "route-116",
    hidden: false,
    type: "berry",
  },
  {
    name: "pinap-berry",
    coordinates: [1096, 2072],
    amount: 3,
    location: "route-116",
    hidden: false,
    type: "berry",
  },
  {
    name: "x-special",
    coordinates: [1640, 2234],
    amount: 1,
    location: "route-116",
    hidden: false,
    type: "item",
  },
  {
    name: "black-glasses",
    coordinates: [1880, 2248],
    amount: 1,
    location: "route-116",
    hidden: true,
    type: "item",
  },
  {
    name: "hp-up",
    coordinates: [2040, 2170],
    amount: 1,
    location: "route-116",
    hidden: false,
    type: "item",
  },
]
