import { pgEnum } from "drizzle-orm/pg-core"

// TODO: finish
export const pgTrainerClass = pgEnum("trainer-class", [
  "pkmn-trainer-1",
  "pkmn-trainer-2",
  "hiker",
  "team-aqua",
  "pkmn-breeder",
  "cooltrainer",
  "bird-keeper",
  "collector",
  "swimmer-m",
  "team-magma",
  "expert",
  "aqua-admin",
  "black-belt",
  "aqua-leader",
  "hex-maniac",
  "aroma-lady",
  "ruin-maniac",
  "interviewer",
  "tuber-f",
  "tuber-m",
  "lady",
  "beauty",
  "rich-boy",
  "pokemaniac",
  "guitarist",
  "kindler",
  "camper",
  "picnicker",
  "bug-maniac",
  "psychic",
  "gentleman",
  "elite-four",
  "leader",
  "school-kid",
  "sr-and-jr",
  "winstrate",
  "pokefan",
  "youngster",
  "champion",
  "fisherman",
  "triathlete",
  "dragon-tamer",
  "ninja-boy",
  "battle-girl",
  "parasol-lady",
  "swimmer-f",
  "twins",
  "sailor",
  "cooltrainer-2",
  "magma-admin",
  "rival",
  "bug-catcher",
  "pkmn-ranger",
  "magma-leader",
  "lass",
  "young-couple",
  "old-couple",
  "sis-and-bro",
  "salon-maiden",
  "dome-ace",
  "palace-maven",
  "arena-tycoon",
  "factory-head",
  "pike-queen",
  "pyramid-king",
  "rs-protag",
])

const trainerClasses = pgTrainerClass.enumValues
export type TrainerClass = (typeof pgTrainerClass.enumValues)[number]

export const parseTrainerClass = (input: string) => {
  return trainerClasses.includes(input as TrainerClass) ? (input as TrainerClass) : null
}
