import { pgEnum } from "drizzle-orm/pg-core"

// TODO: finish
const pgTrainerClass = pgEnum("trainer_class", [
  "pkmn_trainer_1",
  "pkmn_trainer_2",
  "hiker",
  "team_aqua",
  "pkmn_breeder",
  "cooltrainer",
  "bird_keeper",
  "collector",
  "swimmer_m",
  "team_magma",
  "expert",
  "aqua_admin",
  "black_belt",
  "aqua_leader",
  "hex_maniac",
  "aroma_lady",
  "ruin_maniac",
  "interviewer",
  "tuber_f",
  "tuber_m",
  "lady",
  "beauty",
  "rich_boy",
  "pokemaniac",
  "guitarist",
  "kindler",
  "camper",
  "picnicker",
  "bug_maniac",
  "psychic",
  "gentleman",
  "elite_four",
  "leader",
  "school_kid",
  "sr_and_jr",
  "winstrate",
  "pokefan",
  "youngster",
  "champion",
  "fisherman",
  "triathlete",
  "dragon_tamer",
  "ninja_boy",
  "battle_girl",
  "parasol_lady",
  "swimmer_f",
  "twins",
  "sailor",
  "cooltrainer_2",
  "magma_admin",
  "rival",
  "bug_catcher",
  "pkmn_ranger",
  "magma_leader",
  "lass",
  "young_couple",
  "old_couple",
  "sis_and_bro",
  "salon_maiden",
  "dome_ace",
  "palace_maven",
  "arena_tycoon",
  "factory_head",
  "pike_queen",
  "pyramid_king",
  "rs_protag",
])

const trainerClasses = pgTrainerClass.enumValues
export type TrainerClass = (typeof pgTrainerClass.enumValues)[number]

const parseTrainerClass = (input: string) => {
  return trainerClasses.includes(input as TrainerClass) ? (input as TrainerClass) : null
}
